### ISSUE TITLE
Like the app, a few suggestions.

### ISSUE THREAD

**Issue by gsxawd99** [pyuan/VolunteerSignInApp#1]
Thanks for the app, very useful. If I may make a few suggestions. Maybe a way to keep the list of people but clear the sign in signatures and re-save ( gives an error now and doesn't clear the signature), and a way to edit the input form (example delete the 18+ field) and edit the field names so they also reflect on the PFD form, like group name rather than team name etc etc., and also maybe making the signature field a little bigger when used in landscape mode. But very useful and helpful, thank you.

**Comment by pyuan** [comment]
Thanks for the feedback, I will take these into consideration for the next update. Thanks
